parameters:
  mailer_user: "%env(MAILER_USER)%"

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: App\Document\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        confirmation:
            enabled: false